### ISSUE TITLE
Running CompilerGym on my own program

### ISSUE THREAD

**Issue by mtc-jwlee** [facebookresearch/CompilerGym#102]
## ❓ Questions and Help

Hi,

From the FAQ, https://facebookresearch.github.io/CompilerGym/faq.html#how-do-i-run-this-on-my-own-program
It says I can run CompilerGym on my own program using the following command:

$ bazel run -c opt //compiler_gym/bin:brute_force -- --env=llvm-v0 --program_data=file:///$PWD/myapp.bc

It seems this doesn't work. If this feature is still supported, could you please tell me how I can run this?

Thanks!

**Comment by ChrisCummins** [comment]
Hi @mtc-jwlee, thanks for the report! That documentation is out of date. The `--program_data` flag has changed to `--benchmark`. Full example:

```sh
# The latest development build is required
git pull origin development
# Make a bitcode file to use as an example:
echo 'int main() {return 0;}' > myapp.c
clang-10 -emit-llvm -c myapp.c

# Use --benchmark=file:////path/to/file to use it with CompilerGym:
bazel run -c opt //compiler_gym/bin:random_search -- --env=llvm-ic-v0 --benchmark=file:///$PWD/myapp.bc
```

Programmatically you can use [env.make_benchmark(...)](https://facebookresearch.github.io/CompilerGym/llvm/api.html#compiler_gym.envs.llvm.make_benchmark) to load your own programs:

```py
import gym
import compiler_gym
from pathlib import Path

env = gym.make("llvm-ic-v0")
benchmark = env.make_benchmark(Path("./myapp.bc").absolute())
env.reset(benchmark=benchmark)
print(env.ir)
```

Hope that helps!

Cheers,
Chris

**Comment by mtc-jwlee** [comment]
@ChrisCummins Thank you so much, Chris. This works great!!
