### ISSUE TITLE
Got the following error: ValueError: Unknown benchmark "file:////home/gfursin/work/susan.bc"

### ISSUE THREAD

**Issue by gfursin** [facebookresearch/CompilerGym#12]
Hi,

Thank you for the project - looks very interesting!

I got stuck with the following example (https://github.com/ctuning/reproduce-milepost-project/issues/11):

```
import gym
import compiler_gym
env = gym.make("llvm-v0")
env.reset(benchmark="file:////home/gfursin/work/susan.bc")
env.observation["ProGraML"]
env.observation["Inst2vec"]
```

I generated susan.bc but I get the following error:
```
ValueError: Unknown benchmark "file:////home/gfursin/work/susan.bc"
```

Any suggestions how to fix that, please?

Thanks again for your project,
Grigori

**Comment by ChrisCummins** [comment]
Hi @gfursin,

Woops! sorry about that, I wrote that comment late last night and forgot the API :)

To load the file `~/work/susan.bc` you first need to define a `Benchmark` object:
```py
import compiler_gym
from compiler_gym.service.proto import Benchmark, File

path = "/home/gfursin/work/susan.bc"
benchmark = Benchmark(uri=f"file:///{path}", program=File(uri=f"file:///{path}"))
```

You can then start a compiler session for that benchmark:

```py
import gym
env = gym.make("llvm-v0")
env.reset(benchmark)
```

And then query the various [program representations](https://facebookresearch.github.io/CompilerGym/llvm/index.html#observation-spaces) using:

```py
>>> env.observation["Ir"]
# '; ModuleID = ...

env.observation["Programl"]
# <networkx.classes.multidigraph.MultiDiGraph object at 0x7f9d8050ffa0>

env.observation["Inst2vec"]
# array([[-0.26956588,  0.47407162, -0.36637706, ..., -0.49256894, ...

env.observation["Autophase"]
# array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, ...
```

Cheers,
Chris

**Comment by ChrisCummins** [comment]
One wrinkle is that CompilerGym is built against LLVM-10, and backwards compatibility of bitcodes is not guaranteed. If you encounter errors on `env.reset(benchmark)`, it may a compatibility issue. If possible, compile the bitcode using clang-10:

```
$ clang-10 -emit-llvm -c susan.c
```

Or in the case of the `susan` benchmark, we have builtin support for the [cBench suite](https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/third_party/cBench) ;-)

```py
import gym
import compiler_gym
env = gym.make("llvm-v0")
env.require_dataset("cBench-v0")
env.reset(benchmark="cBench-v0/susan")
```

Cheers,
Chris

**Comment by gfursin** [comment]
Nice! 
Thanks a lot @ChrisCummins - it worked fine now!!! 
Cool to see the cBench suite there too ;) !
I will continue playing with the framework ...

**Comment by ChrisCummins** [comment]
Just a follow up on this, I have added a [env.make_benchmark()](https://facebookresearch.github.io/CompilerGym/llvm/api.html#compiler_gym.envs.llvm.make_benchmark) API to the [v0.1.1 release](https://github.com/facebookresearch/CompilerGym/releases/tag/v0.1.1) so that it is easier to create benchmarks now. You can just pass in a list of .c/.cc/.bc files and they will be compiled and linked into an LLVM module:

```py
import gym
import compiler_gym
env = gym.make("llvm-v0")
benchmark = env.make_benchmark(["susan.c"])  # takes a list of .c, .cc, .bc files
env.reset(benchmark=benchmark)
```

Cheers,
Chris

**Comment by gfursin** [comment]
Cool!
I tried the new version and it works.
I just had to change ```make_dataset``` to ```make_benchmark``` in your example above - I think there is a typo ;) ...
Thanks, Chris!

**Comment by farhaninfinitybits** [comment]
Hi @ChrisCummins,
make_benchmark() is not working on a C program.
It's throwing some runtime error.
Any suggestions how to fix it, please?

**Comment by ChrisCummins** [comment]
> Hi @ChrisCummins,
> make_benchmark() is not working on a C program.
> It's throwing some runtime error.
> Any suggestions how to fix it, please?

Hi @farhaninfinitybits,

could you please post the code snippet you used, and the error that was produced? On my system, the following works:

```
$ echo 'int main() {}' > foo.c
$ python
>>> import compiler_gym
>>> import gym
>>> env = gym.make("llvm-v0")
>>> benchmark = env.make_benchmark('foo.c')
```

Cheers,
Chris

**Comment by farhaninfinitybits** [comment]
Hi @ChrisCummins,

I was getting this `RuntimeError: freeze_support()` error.
I have looked into this error and found that it was due to multithreading. So I have to guard code by
`if __name__ == "__main__":`
And it worked
Thanks

**Comment by ChrisCummins** [comment]
Interesting, thanks for following up!

Cheers,
Chris
