### ISSUE TITLE
Need eval_policy to operate on environments with observations

### ISSUE THREAD

**Issue by JD-ETH** [facebookresearch/CompilerGym#142]
## 🚀 Feature

Add observation type to `eval_policy`.  Add a field in Write-up where submitter has to specify whether and which observation they have used for the algorithm. 

## Motivation

Currently the eval_policy has a hard coded environment of `llvm-lc-v0`. For someone who wants to submit to the leaderboard, using any of the provided features this will fail the evaluation process. 

## Pitch

Allow observation to be used.

**Comment by JD-ETH** [comment]
I realized you can access observations by calling env.observation["Autophase"].

**Comment by ChrisCummins** [comment]
He @JD-ETH, you're right, you can use `env.observation[...]` to grab an observation at any time, but the most efficient way to do this is actually to set `env.observation_space = ...` on the `env` instance you receive. This isn't clear in the example code so far so I'm re-opening this as a reminder to myself to improve the documentation. :-) Thanks!

**Comment by ChrisCummins** [comment]
Documented in https://facebookresearch.github.io/CompilerGym/compiler_gym/leaderboard.html#compiler_gym.leaderboard.llvm_instcount.eval_llvm_instcount_policy
