### ISSUE TITLE
Add support for loading URLs to CompilerEnvStateReader.read_paths()

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#148]
## 🚀 Feature

Extend [CompilerEnvStateReader.read_paths()](https://github.com/facebookresearch/CompilerGym/blob/de07d4867e0bb0b47f6fa4bce5e262ea8f014c3e/tests/compiler_env_state_test.py#L212-L335) so that any combination of file path or URL can be loaded.

**Comment by venkateshtata** [comment]
Hey @ChrisCummins , can I take up this issue and work on it ?

**Comment by ChrisCummins** [comment]
Hi @venkateshtata, yes, I would be very happy for you to take a look at this! Feel free to ask questions/discuss here.

Cheers,
Chris

**Comment by venkateshtata** [comment]
> ## 🚀 Feature
> Extend [CompilerEnvState.read_csv_file(...)](https://github.com/facebookresearch/CompilerGym/blob/2623458424faa553df43e63f7b00bf5e45aade3f/compiler_gym/compiler_env_state.py#L87) so that any combination of file path or URL can be loaded.

Hi @ChrisCummins, I am not able to find the function `read_csv_file` defined within the `compiler_env_state.py` file under `development` branch in order to edit the function. Do I have to fork a specific branch to get it ? could you please let me know where to start. Thank you.

**Comment by ChrisCummins** [comment]
Ah, good catch, sorry! The function was renamed in v0.1.8 to [CompilerEnvStateReader.read_paths()](https://github.com/facebookresearch/CompilerGym/blob/de07d4867e0bb0b47f6fa4bce5e262ea8f014c3e/tests/compiler_env_state_test.py#L212-L335). As you can see it takes a list of string arguments - you would be extending this to support handling http(s)-type URLs.

Tests for that class can be found [here](https://github.com/facebookresearch/CompilerGym/blob/de07d4867e0bb0b47f6fa4bce5e262ea8f014c3e/tests/compiler_env_state_test.py#L212-L335), though I see that this method does not have any test coverage yet, so that would be another good thing to land!

Be sure to check out the [contributing guide](https://github.com/facebookresearch/CompilerGym/blob/development/CONTRIBUTING.md#pull-requests) for other details.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Hi @venkateshtata, just following up :-) Did you make any progress on this?

Cheers,
Chris

**Comment by nluu175** [comment]
Hi @ChrisCummins , I would like to work on this feature!

**Comment by ChrisCummins** [comment]
Hi @nluu175, @thecoblack wrote a PR to address this #692
