### ISSUE TITLE
Use round-robin ordering for leaderboard experiment execution

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#243]
## 🚀 Feature

Don't repeat all `--n` runs of each benchmark in order, perform 1 run of each benchmark, then proceed to the 2nd run, etc, until all `n` runs have been completed.

**Comment by thecoblack** [comment]
Hey! I was checking this repo and I was wondering if you would like some help :P. I am a bit new contributing to open source so lmk if I can help.

**Comment by ChrisCummins** [comment]
Hi @thecoblack, great, thanks for offering to help!

Are you new to development in general or just new to open source? This particular issue may be more advanced then some of the others. I would suggest #148 might be a more suitable starting point.

Cheers,
Chris

**Comment by thecoblack** [comment]
I'm just new to open source. Regarding the issue, I've already checked this issue and I might have a solution, but i will check the other one too :). 

Thanks!
