### ISSUE TITLE
Problem registering environment with RLlib that use wrapper functions with cbench dataset

### ISSUE THREAD

**Issue by phesse001** [facebookresearch/CompilerGym#304]
## 🐛 Bug

Hello,

I am having trouble using the cbench dataset within RLlib. I went through the example you provide for using RLlib with compiler gym and got no errors. However, when I switch the training dataset from npb to cbench, I get a `TypeError: cannot pickle '_thread.lock' object`. This seems to be a result of passing it through the wrapper function as the evironment works with cbench if I don't use the wrapper function to make the benchmarks cycle.

## To Reproduce

1. Open jupyter notebook environment and navigate to CopilerGym/examples/rllib.ipynb
2. execute all cells up to cell titled "Datasets"
3. under `chstone = env.datasets["chstone-v0"]` add line `cbench = env.datasets["cbench-v1"]`
4. change `train_benchmarks = list(islice(npb.benchmarks(), 55))` to `list(cbench.benchmarks())`
5. execute cell and execute cell below that creates function `make_training_env(*args)` to cycle over training benchmarks

## Error message

TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/ray/cloudpickle/__init__.py in dumps_debug(obj, *args, **kwargs)
     38     try:
---> 39         return dumps(obj, *args, **kwargs)
     40     except (TypeError, PicklingError) as exc:

~/.local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     72             )
---> 73             cp.dump(obj)
     74             return file.getvalue()

~/.local/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    579         try:
--> 580             return Pickler.dump(self, obj)
    581         except RuntimeError as e:

TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-20-0f25412d3f04> in <module>
      8   return CycleOverBenchmarks(make_env(), train_benchmarks)
      9 
---> 10 tune.register_env("compiler_gym", make_training_env)

~/.local/lib/python3.8/site-packages/ray/tune/registry.py in register_env(name, env_creator)
     85     if not callable(env_creator):
     86         raise TypeError("Second argument must be callable.", env_creator)
---> 87     _global_registry.register(ENV_CREATOR, name, env_creator)
     88 
     89 

~/.local/lib/python3.8/site-packages/ray/tune/registry.py in register(self, category, key, value)
    120             raise TuneError("Unknown category {} not among {}".format(
    121                 category, KNOWN_CATEGORIES))
--> 122         self._to_flush[(category, key)] = pickle.dumps_debug(value)
    123         if _internal_kv_initialized():
    124             self.flush_values()

~/.local/lib/python3.8/site-packages/ray/cloudpickle/__init__.py in dumps_debug(obj, *args, **kwargs)
     45         else:
     46             msg = _warn_msg(obj, "ray.cloudpickle.dumps", exc)
---> 47             raise type(exc)(msg)

TypeError: ray.cloudpickle.dumps(<function make_training_env at 0x7fb3827e3a60>) failed.
To check which non-serializable variables are captured in scope, re-run the ray script with 'RAY_PICKLE_VERBOSE_DEBUG=1'.

## Expected behavior

Same behavior as when using npb as training dataset

## Environment

Please fill in this checklist:

- CompilerGym:
- How you installed CompilerGym (conda, pip, source): pip
- OS: Ubuntu 20.04
- Python version: 3.8.5
- Build command you used (if compiling from source):
- GCC/clang version (if compiling from source):
- Bazel version (if compiling from source):
- Versions of any other relevant libraries:
compiler_gym version: 0.1.9
ray version: 1.4.0
gym version: 0.18.3

## Additional context

I can get it to work by using the src code from the wrapper function directly in the notebook to cycle, but when it is wrapped in a class with the wrapper, it doesn't work for cbench. It does, however work with npb, which I thought was odd.

**Comment by phesse001** [comment]
Right after I created this I noticed there was a PR to make datasets compatible with picke - I'm guessing this would fix my problem. If so, please close this issue. Thanks!

**Comment by ChrisCummins** [comment]
Hi @phesse001, thanks for the report! You are indeed right. Some of the benchmark instances were not pickle compatible, which would break rllib. #302 was specifically to fix this problem, so it should not affect the `development` branch. If you are using an older CompilerGym version, you can work around the problem by changing the line:

```py
train_benchmarks = list(islice(npb.benchmarks(), 55))
```

to be:

```py
train_benchmarks = list(islice(npb.benchmark_uris(), 55))
```

that will use strings instead of [Benchmark](https://facebookresearch.github.io/CompilerGym/compiler_gym/datasets.html#benchmark) class instances.

Cheers,
Chris
