### ISSUE TITLE
[typo] ```pythom -m compiler_gym ... ```

### ISSUE THREAD

**Issue by KKimj** [facebookresearch/CompilerGym#305]
## 📚 Documentation

Hello, 

There is a minor typo in your [document FAQ](https://facebookresearch.github.io/CompilerGym/faq.html).

    https://facebookresearch.github.io/CompilerGym/faq.html

Thanks
Have a nice day!

![image](https://user-images.githubusercontent.com/40026920/123532702-68c19180-d74a-11eb-9b8b-b4144b14c107.png)

**Comment by ChrisCummins** [comment]
Hi @KKimj, good catch, thank you for reporting!

Cheers,
Chris
