### ISSUE TITLE
Reset API endpoint

### ISSUE THREAD

**Issue by sahirgomez1** [facebookresearch/CompilerGym#330]
Undo all actions through a reset call. Required?

**Comment by ChrisCummins** [comment]
IMO, this can achieved through:

1. end current session
2. start new session with the same benchmark/reward

**Comment by sahirgomez1** [comment]
> IMO, this can achieved through:
> 
> 1. end current session
> 2. start new session with the same benchmark/reward

Correct, I'm going to close this issue.
