### ISSUE TITLE
Strange behavior in IrInstructionCountOz reward

### ISSUE THREAD

**Issue by MohamedAlmaki** [facebookresearch/CompilerGym#338]
## ❓ Questions and Help
Can the Oz flag produce a module that has more instructions than the original module? 

## Additional Context
To reproduce the strange behavior: 
I took the commandline of `benchmark://cbench-v1/bitcount ` in [results_p125_t10800.csv](https://github.com/facebookresearch/CompilerGym/blob/development/leaderboard/llvm_instcount/random_search/results_p125_t10800.csv) and split it into two commandlines: 
```py
commandline1 = "opt -functionattrs -globaldce -constmerge -argpromotion -sink -ipconstprop -reassociate -gvn-hoist -loop-reduce -loop-fusion -loop-simplifycfg -loop-unroll -mem2reg -indvars -name-anon-globals -early-cse-memssa -globaldce -dse -aggressive-instcombine -lower-constant-intrinsics -argpromotion -called-value-propagation -simplifycfg -loop-unroll-and-jam -rewrite-statepoints-for-gc -simple-loop-unswitch -early-cse-memssa -sroa -reg2mem -loop-simplifycfg -gvn-hoist -coro-early -memcpyopt -reassociate -sccp -tailcallelim -forceattrs -callsite-splitting -early-cse-memssa -loop-unroll -mem2reg -scalarizer -instcombine -pgo-memop-opt -lower-expect -aggressive-instcombine -mergeicmps -nary-reassociate -globaldce -callsite-splitting -coro-cleanup -globalsplit -simplifycfg -strip-nondebug -strip-dead-prototypes -inject-tli-mappings -strip -post-inline-ee-instrument input.bc -o output.bc"
# last ten passes
commandline2 = "opt -coro-elide -tailcallelim -libcalls-shrinkwrap -consthoist -rpo-functionattrs -redundant-dbg-inst-elim -sccp -libcalls-shrinkwrap -loop-versioning -elim-avail-extern input.bc -o output.bc"
```
Then, I applied the first commandline: 
```py
env = gym.make("llvm-ic-v0")
env.reset(benchmark="benchmark://cbench-v1/bitcount")
print(env.observation["IrInstructionCount"])
print(env.observation["IrInstructionCountO0"])
print(env.observation["IrInstructionCountOz"])
print(env.step(env.commandline_to_actions(commandline1)))
print(env.observation["IrInstructionCount"])
```
The output is: 
```
857
857
405
(None, 1.0044247787610618, False, {'action_had_no_effect': False, 'new_action_space': False})
403
```
The reward is as expected. `(857 - 403) / max(857-405, 1) = 1.0044247787610618`
But when I save the bitcode, reload it again in anthor benchmark and run the second command: 
```py 
env.write_bitcode("bitcount-first.bc")
benchmark = Benchmark.from_file(uri="bitcount-first", path="bitcount-first.bc")
env = gym.make("llvm-ic-v0")
env.reset(benchmark=benchmark)
print(env.observation["IrInstructionCount"])
print(env.observation["IrInstructionCountO0"])
print(env.observation["IrInstructionCountOz"])
print(env.step(env.commandline_to_actions(commandline2)))
print(env.observation["IrInstructionCount"])
```
The output is: 
```
403
403
406
(None, 5.0, False, {'action_had_no_effect': False, 'new_action_space': False})
398
```
The reward will not be normalized because `IrInstructionCountOz` is bigger than `IrInstructionCountO0`. The reward will be `(403-398) / max(403 - 406, 1) = 5/1 = 5`. 
The general behavior of the command line is reserved so if you run the whole command line the reduction will be the same: 
```py 
env = gym.make("llvm-ic-v0")
env.reset(benchmark="benchmark://cbench-v1/bitcount")
print(env.observation["IrInstructionCount"])
print(env.observation["IrInstructionCountO0"])
print(env.observation["IrInstructionCountOz"])
print(env.step(env.commandline_to_actions(commandline)))
print(env.observation["IrInstructionCount"])
```
The output: 
```
857
857
405
(None, 1.0154867256637168, False, {'action_had_no_effect': False, 'new_action_space': False})
398
```
which is as expected `(857-398) / max(857-405, 1) = 1.0154867256637168`

**Comment by ChrisCummins** [comment]
Hi @MohamedAlmaki,

Great question!

> Can the Oz flag produce a module that has more instructions than the original module?

Yes. The goal of `-Oz` is to produce small binaries, without any guarantees.

> But when I save the bitcode, reload it again in anthor benchmark and run the second command ... The reward will not be normalized because IrInstructionCountOz is bigger than IrInstructionCountO0

This is intentional, though perhaps not well explained in the documentation. The scaling factor for `IrInstructionCountOz` is determined at [Benchmark construction time](https://github.com/facebookresearch/CompilerGym/blob/a5341616712f6395eeb88d10b3657625e33ca9e1/compiler_gym/envs/llvm/service/Cost.cc#L199-L234). This means that if you split a sequence of actions into subgroups and create a new benchmark after each group, the rewards *may not be the same* as if you ran each subgroup on the same Benchmark instance.

Perhaps you could use a simpler reward formulation that is just `IrInstructionCountOz` of the original module / `IrInstructionCount` of the final module? In your example, that would be `405 / 398 = 1.01758794`.

Cheers,
Chris

**Comment by MohamedAlmaki** [comment]
> Yes. The goal of -Oz is to produce small binaries, without any guarantees.

Okay.

> Perhaps you could use a simpler reward formulation that is just IrInstructionCountOz of the original module / IrInstructionCount > of the final module? In your example, that would be 405 / 398 = 1.01758794.

Yes, I can but the same problem happens here. I was thinking of a way to combine the reward of the two environments. Maybe,  moving the reward object from one environment to another. But the problem is that you can't set the reward object, you can only access it using the reward view. Or I can just calculate the final result manually outside the environments. 

Thanks for your response. 

Regards,
Mohammed Almakki

**Comment by ChrisCummins** [comment]
Hi @MohamedAlmaki,

> I was thinking of a way to combine the reward of the two environments.

Yes, it is unfortunately not possible to change the `-Oz` scale factor on an ad-hoc basis. What I'm suggesting is to ignore the reward value entirely and compute your own values:

```py
import compiler_gym

reference_env = compiler_gym.make("llvm-v0")
reference_oz_ic = reference_env.observation.IrInstructionCountOz()
... # do what you like here

# Once done, compute raw instruction count on the final environment:
final_ic = new_env.observation.IrInstructionCount()

print("My performance relative to -Oz is:", reference_oz_ic / final_ic).
```

**Comment by MohamedAlmaki** [comment]
Yes, this is the way I'm doing it right now. Thanks for your response. 
I will close this now.
