### ISSUE TITLE
Rename Reward.id to Reward.name

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#381]
## 🚀 Feature

The `Reward` class is unusual in that its name attribute is called `id`. We should rename this to `name` to be consistent with all of the other space classes.

## Motivation

To be consistent.

**Comment by PuneetDabral** [comment]
sir can i do my first contribution here ...but i need your support

**Comment by ChrisCummins** [comment]
Hi @PuneetDabral, great! I can help you.

The first thing to do would be to follow the [install instructions](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#building-from-source) to build CompilerGym from source on your local machine.

The Reward class can be found in `compiler_gym/spaces/reward.py`. The job of this task is to rename the [Reward.id](https://github.com/facebookresearch/CompilerGym/blob/5354dddb18e721b55335434524bd2fa72fb3ca2e/compiler_gym/spaces/reward.py#L84) attribute.

It might take a while to check through the source code for occurrences of the `id` name. Be sure to run the unit tests, they will help.

Good luck! Let me know if you have any questions.

Cheers,
Chris

**Comment by PuneetDabral** [comment]
sir i changed self.id=name now what i can do?? can you please guide me
