### ISSUE TITLE
Taking Runtime observation repeatedly gets slower over time

### ISSUE THREAD

**Issue by aymanizz** [facebookresearch/CompilerGym#393]
## 🐛 Bug

After creating an environment, taking the runtime observation from the same environment progressively takes more time to compute.

Log from the MRE below:
```
Completed in 61.9ms
Completed in 60.3ms
Completed in 92.3ms
Completed in 63.4ms
Completed in 60.7ms
Completed in 64.7ms
...
Completed in 223.1ms
Completed in 252.4ms
Completed in 237.7ms
Completed in 219.0ms
Completed in 221.4ms
Completed in 235.5ms
```

## To Reproduce

1. Create an environment.
2. Repeatedly take the runtime observation.

```python
import gym
import compiler_gym
from compiler_gym.util.timer import Timer

with gym.make('llvm-v0') as env:
    env.reset(benchmark='benchmark://cbench-v1/bitcount')
    while True:
        with Timer(f'Completed'):
            env.observation.Runtime()
```

## Expected behavior

Taking the runtime observation repeatedly shouldn't get slower progressively.

## Environment

- CompilerGym: development branch
- How you installed CompilerGym (conda, pip, source): source
- OS: Ubuntu 18.04 LTS
- Python version: 3.9.6
- Build command you used (if compiling from source): `make bdist_wheel-linux`

**Comment by ChrisCummins** [comment]
Hi @aymanizz, thanks for the report, and for the minimal repro script! I was able to successfully reproduce the problem on my end. Let me take a look a look at this next week and get back to you.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Just a quick update on this: I have traced the source of the problem to the `subprocess:Popen()` library command that I am using to execute compiled binaries. When called many thousands of times in a tight loop its runtime slows down with each successive call.

I have a patch that fixes the issue by replacing `subprocess:Popen()` with `boost::process`. After a couple more days of testing and refinement I will open a pull request for this and merge the fix into the development branch.

Cheers,
Chris

**Comment by aymanizz** [comment]
Thanks, Chris. That's great!

We've also noticed a gradual RAM usage increase (although slow) using the same code snippet above, not sure if this is an issue though. Can you try that on your end?

**Comment by ChrisCummins** [comment]
Thanks for the report @aymanizz. I have checked the RAM usage and run time of my fix for this and everything seems stable, with RAM usage fixed at 32MB:

```
Loop time =    0s   Iteration =        1   Last wall time = 29.2ms   Last runtimes = [0.95  0.913 0.89 ]
Loop time =    3s   Iteration =      475   Last wall time = 6.3ms   Last runtimes = [0.875 1.008 0.91 ]
Loop time =    6s   Iteration =      946   Last wall time = 6.3ms   Last runtimes = [0.95  0.908 0.888]
Loop time =    9s   Iteration =    1,420   Last wall time = 6.3ms   Last runtimes = [0.936 0.903 0.903]
...
Loop time =  129s   Iteration =   20,458   Last wall time = 6.3ms   Last runtimes = [0.947 0.928 0.908]
Loop time =  132s   Iteration =   20,930   Last wall time = 6.3ms   Last runtimes = [0.906 0.933 0.91 ]
Loop time =  135s   Iteration =   21,401   Last wall time = 6.3ms   Last runtimes = [0.908 0.887 0.982]
Loop time =  138s   Iteration =   21,876   Last wall time = 6.1ms   Last runtimes = [0.882 0.899 0.895]
Loop time =  141s   Iteration =   22,352   Last wall time = 6.2ms   Last runtimes = [0.898 0.912 0.941]
...
Loop time =  691s   Iteration =  109,224   Last wall time = 6.3ms   Last runtimes = [0.888 0.941 0.911]
Loop time =  694s   Iteration =  109,694   Last wall time = 6.3ms   Last runtimes = [0.915 0.928 0.918]
Loop time =  697s   Iteration =  110,162   Last wall time = 6.5ms   Last runtimes = [0.906 0.949 0.952]
Loop time =  700s   Iteration =  110,628   Last wall time = 6.5ms   Last runtimes = [0.942 0.973 0.932]
Loop time =  703s   Iteration =  111,096   Last wall time = 6.5ms   Last runtimes = [0.919 0.925 0.927]
Loop time =  706s   Iteration =  111,562   Last wall time = 6.4ms   Last runtimes = [0.91  0.903 0.961]
```

I am applying some finishing touches before merging #398, then will let you know when its safe to pull the latest development branch.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
#398 has been merged into development. Please update and let me know if you are able to reproduce the problem.

Cheers,
Chris
