### ISSUE TITLE
Make the "example compiler gym service" work without bazel

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#412]
## 🚀 Feature

The example of how to add a new compiler service in `examples/example_compiler_gym_service` requires bazel to run. It would nice if it could instead be run standalone, as bazel isn't familiar to everyone and can be confusing to debug when it fails.

Also the the README.md file is out of date.

Thanks to @mostafaelhoushi for the report.

**Comment by mostafaelhoushi** [comment]
I first read the title as:

> Make the "example compiler gym service" great again
