### ISSUE TITLE
Possible error in how to generate unbiased benchmarks

### ISSUE THREAD

**Issue by hughleat** [facebookresearch/CompilerGym#422]
## 📚 Documentation
(Possible error, possibly me doing it wrong)
https://facebookresearch.github.io/CompilerGym/compiler_gym/datasets.html

The code for `random_benchmark` says:

```python
rng = np.random.default_rng()
finite_datasets = [d for d in env.datasets if len(d) != math.inf]
dataset = rng.choice(
    finite_datasets,
    p=[len(d) for d in finite_datasets]
)
dataset.random_benchmark(random_state=rng)
```

But, I think that if you call `len` on a generator, it will fail with error:
`TypeError: 'float' object cannot be interpreted as an integer`

Suggest changing it to:
`d.size != math.inf`

**Comment by ChrisCummins** [comment]
Thanks for the report @hughleat! `len()` can't return a float, and `math.inf` is a float. I filed a bug for this back in #303 but missed the example doc you have reported. It can be simplified to something like:

```py
rng = np.random.default_rng()
datasets = list(env.datasets())
dataset = rng.choice(datasets, p=[len(d) for d in datasets])
dataset.random_benchmark(random_state=rng)
```

Cheers,
Chris
