### ISSUE TITLE
Observation 'Bitcode' without going through a temporary file.

### ISSUE THREAD

**Issue by hughleat** [facebookresearch/CompilerGym#426]
## 🚀 Feature

Have an observation which just returns the bytes of the bitcode, rather than the file. Going through a temporary file is a (tiny) bit annoying.

```
env.observation["Bitcode"] -> bytes
env.bitcode == env.observation["Bitcode"]
```
## Motivation

I'm passing bitcode to LLVM tools. They will accept bitcode on stdin and emit it to stdout. No need for a temporary file.

## Pitch

Don't use a file when a `bytes` will do? 

## Alternatives

Keep using a file.

**Comment by ChrisCummins** [comment]
Yep, this is a good idea. Happy to take this if you want, will only take a few min.

Cheers,
Chris
