### ISSUE TITLE
More Accurate Runtime Measurement

### ISSUE THREAD

**Issue by mostafaelhoushi** [facebookresearch/CompilerGym#448]
## 🚀 Feature

Make `Timer` measure time in a more accurate way

## Motivation

I have noticed that the [`Timer` class](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/util/timer.py) that is used to measure runtime uses Python's `time` function to measure the time before and after running the executable, and this is an inaccurate method to measure time.

## Pitch

We can use a combination of different techniques to measure time. The `Timer` class can take arguments to determine which method to measure time, and to pass parameters to some of these methods:
- repeat the command `N` times, sort the measured times in ascending order, and get the average of the middle `M` times (`N` and `M` could be parameters provided to the constructor of `Timer`, where `M <= N`)
- use tools like `perf` to measure executable time more accurately (this may require creating an additional class, or a class that inherits from `Timer`)

## Alternatives

We may add an option to hack the C code to insert time measurement function calls within the `main()` function of the benchmark. That will be more accurate than measuring time outside the executable. 

## Additional context

N/A

**Comment by ChrisCummins** [comment]
Thanks for the report @mostafaelhoushi! Yes, `compiler_gym.util.timer.Timer` is just meant for logging / debugging and not for taking accurate runtime measurements. If you could provide a pointer to where that is used in the codebase that would be helpful.

Cheers,
Chris

**Comment by mostafaelhoushi** [comment]
> Thanks for the report @mostafaelhoushi! Yes, `compiler_gym.util.timer.Timer` is just meant for logging / debugging and not for taking accurate runtime measurements. If you could provide a pointer to where that is used in the codebase that would be helpful.
> 
> Cheers, Chris

My understanding that it is being used here by Cbench to measure execution time. Is there another class/function in CompilerGym to measure time more accurately? 
https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/datasets/cbench.py#L182-L227

**Comment by ChrisCummins** [comment]
Ah I see! That code is a little misleading (its leftover from before the new Runtime implementation). The wall time returned by that `_compile_and_run_bitcode_file()` function is never actually used anywhere. The Runtime observation for LLVM environments is measured [in the C++ backend](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/service/Benchmark.cc#L238-L242) using `std::chrono::steady_clock`.

Cheers,
Chris

**Comment by mostafaelhoushi** [comment]
OK. I see. And it is probably running multiple times and taking the average. 
OK. Will close the issue then.

**Comment by ChrisCummins** [comment]
The `Runtime` observation space runs the command for a user-specifiable *n* times (and does *m* warmup runs) and returns an array of measurements:

```py
In [1]: import compiler_gym

In [2]: env = compiler_gym.make("llvm-v0")

In [3]: env.reset()

In [4]: env.runtime_observation_count = 10

In [5]: env.runtime_warmup_runs_count = 3

In [6]: env.observation.Runtime()
[0.212, ...]
```

We don't currently support using `Runtime` as a reward, only as an observation space, so we have no opinion on how to aggregate the numbers. When we do add support (#370) we should provide plenty of options. I like your suggestion of averaging over the middle *m* runtimes.

Cheers,
Chris
