### ISSUE TITLE
Redesign of DataSet API

### ISSUE THREAD

**Issue by hughleat** [facebookresearch/CompilerGym#45]
Redesign the Dataset class to not depend on tar balls and particular data structures.

Currently the datasets are hard coded as tarballs - https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/datasets.py
these later get unpacked into a particular format where the directory structure is very important.

This means that we have to curate them. E.g. we can't pull benchmarks from Anghabench directly, we have to host a tarball somewhere.

Also, if we had random program generators, e.g. CSmith, CLGen, we couldn't really work with them.

Instead, add methods to the Dataset class to install and extract:
```py
class Dataset:
  ...
  def name() -> String
  def install(path_to_use: Path)    # e.g. ~/.compiler_gym/datasets/<name>
  def benchmark_ids() -> Iterable[Any] # Possibly lazy list of benchmark names
  def benchmarks() -> Iterable[Benchmark] # Possibly lazy list of benchmarks
  def benchmark(id: Any) -> Benchmark

class TarballDataset(Dataset):
  def __init__(name: String, url: Stirng, etc..)
  def install(p): download_unpack(p, url)
  def benchmark_ids(): get_filenames_from_install_dir()
  ...

class Anghabench(Dataset):
  ...
  def name(): return "anghabench"
  def install(p): git_clone_into(p, "https://github.com/brenocfg/AnghaBench.git")
  
class CSmith(Dataset):
  def install(p): install_csmith_binary(p)
  def benchmark_ids(): range_all_ints
  def benchmark(id: int): csmith_for_seed(id)

```

At the same time, something like this would free datasets to have their own directory structure. This might be useful when considering input data for correctness and performance. Sometimes multiple benchmarks will share things.

At init time, the gym could look in the dataset dir (e.g. ~/.compiler_gym/datasets or [ENV COMPILER_GYM_DIR]). Any python scripts in there could be run to register datasets.
Programmatically, people could register their own datasets, outside of that common mechanism.
A command line tool, `install_dataset url`, could fetch a script from the url, drop it in the dataset dir, then run install.

**Comment by ChrisCummins** [comment]
Thanks @hughleat, I think that a python-side dataset API makes a lot of sense, and I like the class hierarchy you're proposing. I think a prerequisite for this is to figure out the role of the backend service in managing datasets as at the moment, the frontend python code and backend service have slightly jumbled and overlapping roles. We could shift the responsibility of managing benchmarks from the service to the frontend by:

1. Removing the list-of-all-benchmarks from the [BenchmarkFactory](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/service/BenchmarkFactory.h#L30-L38) in the backend service.
2. Remove the benchmark management methods from the [service API](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/service/proto/compiler_gym_service.proto#L37-L38).
3. Make the `benchmark` a compulsory parameter for starting episodes.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
I think it would be a good idea also to wrap the [Benchmark](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/service/proto/compiler_gym_service.proto#L291-L303) proto with a python class that can add extra functionality like the ability to validate benchmark behavior etc. To begin with, something simple like:

```py
class Benchmark(object):
  def __init__(self, proto: BenchmarkProto)
  def sha1(self) -> bytes  # Name for caching benchmark+any other attributes
  def program_data(self) -> BenchmarkProto  # The data that the service needs
  def program_data_sha1(self) -> bytes  # Used for caching benchmarks on service-side
  def is_validatable(self) -> bool
  def validation_callbacks(self) -> List[Callback[[CompilerEnv], Optional[str]]  # Run any ad-hoc validation, e.g. difftest, valgrind, etc
```

**Comment by ChrisCummins** [comment]
# Upgrade Roadmap

I'd like to propose the following roadmap for deprecating the current dataset API and introducing the new one. Given that it's a pretty high priority feature, there is an aggressive roadmap for deprecating the current API:

## v0.1.4

Add deprecation notices to the existing API but leave the functionality unchanged. Specifically:

- [x] Rename `Dataset` to `LegacyDataset`.
- [x] Add a deprecation notice to `GetBenchmark()` in the `CompilerGymService` RPC interface.
- [x] Add deprecation warnings to `activate()`, `deactivate()`, `delete()`. These deprecation notices will also appear in the documentation. This will cause warnings to be printed when those methods are invoked, e.g.:

```
$ python -m compiler_gym.bin.datasets --env=llvm-v0 --delete=cBench-v0
/home/cec/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/compiler_gym-0.1.3-py3.8.egg/compiler_gym/bin/datasets.py:244: DeprecationWarning: Call to deprecated function (or staticmethod) delete. (Deleting datasets will be removed in v0.1.5. `More information <https://github.com/facebookresearch/CompilerGym/issues/45>`_.) -- Deprecated since version 0.1.4.
  delete(env, name)
llvm-v0 benchmarks site dir: /dev/shm/compiler_gym_runfiles/llvm/10.0.0/bitcode_benchmarks

+-------------------+--------------+-----------------+----------------+
| Active Datasets   | License      | #. Benchmarks   | Size on disk   |
+===================+==============+=================+================+
| cBench-v1         | BSD 3-Clause | 23              | 10.1 MB        |
+-------------------+--------------+-----------------+----------------+
...
```

## v0.1.8

- [ ] Add the new `Dataset` class and all `LegacyDataset` usage over to this.
- [ ] Update the "Getting started guide" and all documentation to refer to the new `Dataset` class and operations.
- [ ] Remove `LegacyDataset` class.
- [ ] Remove the deprecated methods from the documentation: `activate()`, `deactivate()`, `delete()`.
- [ ] Add an example of how to define your own dataset to the documentation.
- [ ] Change the behavior of `activate()`, `deactivate()`, `delete()` to raise an error if invoked, e.g.:

```
$ python -m compiler_gym.bin.datasets --env=llvm-v0 --delete=cBench-v0
error: The delete operation for datasets was removed in v0.1.5.
There is no longer any need to delete datasets.  For more information, see:
<https://github.com/facebookresearch/CompilerGym/issues/45>.
```

## No earlier than v0.1.9

- [ ] Remove the deprecated operations entirely: `activate()`, `deactivate()`, `delete()`. E.g.:

```
$ python -m compiler_gym.bin.datasets --env=llvm-v0 --delete=cBench-v0
FATAL Flags parsing error: Unknown command line flag 'delete'.
```

**Comment by ChrisCummins** [comment]
This is now done and will ship in v0.1.8.

Cheers,
Chris
