### ISSUE TITLE
Following the installation instructions does not work

### ISSUE THREAD

**Issue by ImanHosseini** [facebookresearch/CompilerGym#481]
## 🐛 Bug

Following the instructions here: https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md
I get:
```
Could not find a version that satisfies the requirement loop-tool-py==0.0.7 (from compiler_gym) (from versions: 0.0.3, 0.0.4, 0.0.5, 0.0.6)
ERROR: No matching distribution found for loop-tool-py==0.0.8
```
"CompilerGym requires Python >= 3.6. The binary works on macOS and Linux (on Ubuntu 18.04, Fedora 28, Debian 10 or newer equivalents)." -> I am on Python 3.8 and Ubuntu 20.04 (WSL2).

**Comment by ChrisCummins** [comment]
Hi @ImanHosseini, thanks for the report. That's odd. Can you confirm what command you run to produce this error?

@bwasti, do you know of any issue with dependency resolution for loop-tool-py on WSL2 / py3.8?

Cheers,
Chris

**Comment by ImanHosseini** [comment]
I tried: "pip install -U compiler_gym" and "python3 -m pip install -U compiler_gym"

**Comment by ChrisCummins** [comment]
I can't repo on my local machine or [in colab](https://colab.research.google.com/drive/1HRwdCxucQA5MzonvqRaGWAOHokW3XXbi?usp=sharing). Any chance you could try a clean conda environment? Else there is a docker image available.

Cheers,
Chris

**Comment by ImanHosseini** [comment]
hmm, I had 0.0.6 installed and it was using some cache, not picking up 0.0.7. I manually got the .whl to installed it and works now! Thanks.

**Comment by ChrisCummins** [comment]
That's great to hear, thanks for following up with what worked for you!

Cheers,
Chris

**Comment by sezgin1947** [comment]
Hi I came across to exact same problem with same Python and same Ubuntu version.

I have solved the problem by doing following:

- Removing the the python3-debian package via sudo apt-get remove --auto-remove python3-debian and trying to install CompilerGym with python3 -m pip install compiler_gym==0.2.3

Here is the original source for the solution
https://stackoverflow.com/questions/70570309/pkgresourcesdeprecationwarning-0-1-36ubuntu1-is-an-invalid-version-has-anyone

**Comment by ChrisCummins** [comment]
Hi @sezgin1947, interesting, thanks for providing your fix 🙂 

Cheers,
Chris

**Comment by chunhualiao** [comment]
I encountered the same problem. My solution was to just upgrade my pip to its latest version: 
  python3 -m pip install --upgrade pip
