### ISSUE TITLE
Circular dependency in the built of the compiler_gym python package

### ISSUE THREAD

**Issue by sogartar** [facebookresearch/CompilerGym#488]
Hi @ChrisCummins,
While porting the build to CMake I encountered a circular dependency problem that I don't know why it does not manifest when running the Bazel build.
There is the following dependency chain.
* `//compiler_gym:compiler_gym`
* `//compiler_gym/envs:envs`
* `//compiler_gym/envs/llvm:llvm`
* `//compiler_gym/envs/llvm:specs`
* `//compiler_gym/envs/llvm/service:compiler_gym-llvm-service-bin`
* `//compiler_gym/envs/llvm/service:compiler_gym-llvm-service-prelinked`
* `//compiler_gym/envs/llvm/service:LlvmSession`
* `//compiler_gym/envs/llvm/service:ActionSpace`
* `//compiler_gym/envs/llvm/service/passes:actions_genfiles`
* `//compiler_gym/envs/llvm/service/passes:make_action_space_genfiles`
* `compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py`
* `make_action_space_genfiles.py` imports `compiler_gym.envs.llvm.service.passes.common`, which is a part of the `compiler_gym` Python package that has not been built yet.

`compiler_gym/repo/www/requirements.txt` requires `compiler_gym`. The pip package takes precedence, since it has `__init__.py` and hides the partially built `//compiler_gym:compiler_gym`, because it does not have `__init__.py` yet. Even if `compiler_gym/compiler_gym/__init__.py` is copied before that, it depends on the auto-generated `version.py` and the other nested `__init__.py` scripts that depend on the auto-generated gRPC stuff.

I think the proper way to resolve this is all Python scripts that are used for auto-generation during the building of `//compiler_gym:compiler_gym` to be outside of the package. At a first glance these are
* `compiler_gym.envs.llvm.service.passes.common`
* `compiler_gym.envs.llvm.service.passes.config`

They are not used by other parts of the package and are also excluded from the final pip package.

@ChrisCummins, do you think this is a good way to fix the problem? I can include such a change also in the Bazel rules, while doing the CMake change. Or you would like me to first fix it in Bazel as a separate PR?

**Comment by ChrisCummins** [comment]
Hi @sogartar, great detective work!

> I think the proper way to resolve this is all Python scripts that are used for auto-generation during the building of //compiler_gym:compiler_gym to be outside of the package.

It wouldn't do any harm to move the auto-generation scripts, but there is also no benefit. As you found out, `compiler_gym/envs/llvm/service/passes/*.py` are not included in the final `compiler_gym` package build. Their only job is to generate some C++ headers/sources that are used to compile the LLVM component (see [rule](https://github.com/facebookresearch/CompilerGym/blob/6eac3c1b2a5355bb4ed55f243fb834ccfcdd9fcb/compiler_gym/envs/llvm/service/passes/BUILD#L75-L89)). To workaround the problem of conflicting `compiler_gym` imports we could strip the module names to:

```diff
diff --git a/compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py b/compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py
index 58d5e800..3265525d 100644
--- a/compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py
+++ b/compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py
@@ -81,8 +81,8 @@ import logging
 import sys
 from pathlib import Path
 
-from compiler_gym.envs.llvm.service.passes.common import Pass
-from compiler_gym.envs.llvm.service.passes.config import EXTRA_LLVM_HEADERS
+from common import Pass
+from config import EXTRA_LLVM_HEADERS
 
 logger = logging.getLogger(__name__)
```

I'll submit a PR to do this :-)

BTW, there is [another script](https://github.com/facebookresearch/CompilerGym/blob/6eac3c1b2a5355bb4ed55f243fb834ccfcdd9fcb/compiler_gym/envs/llvm/make_specs.py) which creates a pseudo circular dependency as it generates a python module that is included in the final `compiler_gym` package.

> `compiler_gym/repo/www/requirements.txt` requires `compiler_gym`

Yes, everything in the `www` directory can be considered a standalone project that you can ignore. It pip installs its own version of CompilerGym from PyPi.

Cheers,
Chris

**Comment by sogartar** [comment]
@ChrisCummins, [make_specs.py](https://github.com/facebookresearch/CompilerGym/blob/6eac3c1b2a5355bb4ed55f243fb834ccfcdd9fcb/compiler_gym/envs/llvm/make_specs.py) seems much harder to fix in this manner because it imports a lot of stuff from the `compiler_gym` package.
I am curious how is this resolved in Bazel and does not manifest there.

**Comment by ChrisCummins** [comment]
> I am curious how is this resolved in Bazel and does not manifest there.

The CompilerGym package depends on `make_specs.py` (or rather, the `specs.py` file that it generates), not the other way around:

![deps](https://user-images.githubusercontent.com/1636663/142426854-097a6741-9437-497d-8c90-94ff2ed10d33.png)
```
bazel query --output=graph --notool_deps 'allpaths(//:package, //compiler_gym/envs/llvm:specs.py)' | dot -Tpng > /tmp/deps.png
```

The fact that `make_specs.py` imports a couple of modules from CompilerGym means that it shares a subset of the dependencies of the main package:

https://github.com/facebookresearch/CompilerGym/blob/43398312efec2cfb8b0cd29410ec1975a65888bd/compiler_gym/envs/llvm/make_specs.py#L16-L17

https://github.com/facebookresearch/CompilerGym/blob/43398312efec2cfb8b0cd29410ec1975a65888bd/compiler_gym/envs/llvm/BUILD#L87-L90

When bazel runs the `make_specs.py` script, it sandboxes things and setups up the required __init__.py and PYTHONPATH so that only that only the required dependencies are available.

Without bazel, this approach could be simulated by:

1) Assemble the "core" files for the CompilerGym package.
2) Run the `make_specs.py` script using (1) to generate the `specs.py` file.
3) Add the result of (2) to (1) to create the full package.

Cheers,
Chris

**Comment by sogartar** [comment]
The current approach in CMake is populating one directory structure, when going through the targets. It is not sandboxed. This may cause a failure for example if `compiler_gym::compiler_gym` has passed successfully in a previous build, but then `version.py` gets deleted. It may not be generated before `make_specs.py` runs, causing a failure. I will probably add such a "core" target and `specs` would depend on it.

**Comment by ChrisCummins** [comment]
Sounds like the way to go :)

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Closing as I believe @sogartar has worked around the issue in #498, and now superseded by #506.

Cheers,
Chris
