### ISSUE TITLE
CompilerGym/requirements.txt is invalid

### ISSUE THREAD

**Issue by KyleHerndon** [facebookresearch/CompilerGym#501]
## 🐛 Bug
CompilerGym/requirements.txt is an invalid requirements specification:
- `CompilerGym/requirements.txt` recursively includes `CompilerGyms/compiler_gym/requirements.txt` and `CompilerGyms/examples/requirements.txt`
- `CompilerGyms/compiler_gym/requirements.txt` specifies numpy>=1.19.3
- `CompilerGyms/compiler_gym/requirements.txt` specifies numpy~=1.19.2

## To Reproduce

`python -m pip install -r CompilerGym/requirements.txt` will throw an error regarding conflicting version and even if they don't conflict, it throws an error regarding the requirement being specified twice.

## Expected behavior

Should be an easy fix, but I'm not sure which of the viable fixes is to your preferences. I think everything would work if you picked only one version of 1.19.x, but you could also probably remove the nested requirement on `examples/requirements.txt` and then made a note in `examples/README.md` noting the slightly different requirements.

**Comment by ChrisCummins** [comment]
Thanks for the report @KyleHerndon! I agree, specifying `numpy` dependency in both `compiler_gym/requirements.txt` and `examples/requirements.txt` looks redundant to me. I would suggest extending the range of acceptable numpys in `compiler_gym/requirements.txt` to `numpy>=1.19.0` and removing the dep from `examples/requirements.txt`.

FWIW I am unable to reproduce the error locally on the following versions:
```
$ python --version
Python 3.8.5

$ python -m pip --version
pip 21.0.1 from /Users/chris/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/pip (python 3.8)

$ python -m pip freeze | grep numpy
numpy==1.19.5
```

Cheers,
Chris

**Comment by KyleHerndon** [comment]
Yeah, I discovered that apparently this issue doesn't occur on updated versions of pip. My bad for not including my pip version in my report. 

That said, I agree with the changes you propose.

**Comment by ChrisCummins** [comment]
Perfect, patches welcome! 🙂

Cheers,
Chris
