### ISSUE TITLE
what is e2e process from compiler_gym LLVM  to specific  platform (for example ARM, Hexagon) ?      

### ISSUE THREAD

**Issue by 13301338176** [facebookresearch/CompilerGym#527]
## ❓ Questions and Help

what is e2e process from compiler_gym LLVM  to specific  platform (for example ARM, Hexagon) ? 

compiler_gym LLVM only generate "LLVM IR"  and it is responsibility for "ARM/Hexagon Backend" to generate machine code ?

**Comment by ChrisCummins** [comment]
Hi @13301338176, yep, CompilerGym's LLVM environment takes LLVM IR as input and produces LLVM IR as output. To get your code *in*, you can use [env.make_benchmark()](https://compilergym.com/llvm/api.html#compiler_gym.envs.llvm.make_benchmark). To get the IR *out*, you can use the [env.write_bitcode()](https://compilergym.com/compiler_gym/envs.html#compiler_gym.envs.LlvmEnv.write_bitcode) method or the `Ir`/`Bitcode` observation space:

```py
>>> import compiler_gym

>>> env = compiler_gym.make("llvm-v0")

>>> env.reset()

>>> env.write_bitcode("/tmp/foo.bc")
PosixPath('/tmp/foo.bc')

>>> env.observation.Ir()
'; ModuleID = \'-\'\ns...'
```

You can then lower the bitcode to a binary (e.g. ARM) using clang:
```
clang /tmp/foo.bc -o /tmp/foo
```

Or us something like llvm-as to generate machine assembly. Hope that helps!

Cheers,
Chris

**Comment by 13301338176** [comment]
@Chris,  Thanks you .  good &flexible  design for CompilerGym to  decouple  IR optimization  from native machine code.   I love it.   Beside "phase order optimization" ,  is there any other option do for LLVM IR optimization ?  or any roadmap for deep learning OPs optimization  ?  or  any interface/API   users can use to extend/custom other use case (like DNN Ops)?

**Comment by 13301338176** [comment]
I found :   benchmark = make_benchmark('my_app.c') ,   env = gym.make("llvm-v0"),  env.reset(benchmark=benchmark)
Seems  input is "C" source code ,  are you sure we can use "LLVM IR" as input ?   
if Yes,  what is APIs?  still like    benchmark = make_benchmark('xxx.bc')  ?

**Comment by ChrisCummins** [comment]
> Beside "phase order optimization" , is there any other option do for LLVM IR optimization ?

Not at present, though we are working on a new LLVM environment dedicated to loop optimizations for LLVM, and I know of some third party researchers who are working on a superoptimization environment for LLVM. At the moment, it would be possible to integrate your own IR optimization into the phase ordering environment by dumping the bitcode of the environment, applying your ad-hoc transformation, and then creating a new benchmark from this.

BTW, if you have particular optimizations in mind, we welcome feature requests :-)

> or any roadmap for deep learning OPs optimization ?

The [loop_tool](https://compilergym.com/envs/loop_tool.html) environment enables you to manipulate simple pointwise DL ops.

> or any interface/API users can use to extend/custom other use case (like DNN Ops)?

Yep! You can create your own environment using our `CompilationSession` API. See [this example implementation](https://github.com/facebookresearch/CompilerGym/tree/development/examples/example_compiler_gym_service), and the [API docs](https://compilergym.com/compiler_gym/service.html#the-compilationsession-interface) for more details.

> Seems input is "C" source code , are you sure we can use "LLVM IR" as input ?

Yep, the [make_benchmark()](https://compilergym.com/llvm/api.html#compiler_gym.envs.llvm.make_benchmark) API accepts C/C++ files with `.{c,cc,cpp,cxx}` extensions, LLVM-IR bitcode files with `.bc` extensions, or text format LLVM-IR assembly with `.ll` extensions. I've filed #528 to clarify the docs.

Happy holidays! Apologies I will be slow to respond to messages between now and mid January.

Cheers,
Chris

**Comment by 13301338176** [comment]
Thank you for explanation , Happy holidays!.
