### ISSUE TITLE
Benchmark 'benchmark://cbench-v1/lame' returning None

### ISSUE THREAD

**Issue by phesse001** [facebookresearch/CompilerGym#534]
## ❓ Questions and Help

Hello,

I just tried running the training code that I wrote for a DQN a while back that uses compiler gym, and a couple iterations will run and then I get:

Traceback (most recent call last):
  File "train.py", line 31, in <module>
    train(agent, env)
  File "/home/phesse/compiler-rl/dqn/dqn.py", line 252, in train
    action = agent.choose_action(observation)
  File "/home/phesse/compiler-rl/dqn/dqn.py", line 148, in choose_action
    observation = observation.astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'astype'

I print the benchmark it is using every time, and on this particular failure the current benchmark it was getting was `benchmark://cbench-v1/lame`

I then opened a python shell to see, and sure enough:

>>> import compiler_gym
>>> env = compiler_gym.make("llvm-ic-v0")
>>> obs = env.reset("benchmark://cbench-v1/lame")
>>> print(obs)
None

The weird thing is though, that even on the benchmarks that aren't failing, when I run it in the python shell, every call to env.reset(benchmark=benchmark) returns None (not just cbench).

I am using the latest version of compiler gym and can give more details if needed.

Thanks!

**Comment by ChrisCummins** [comment]
Hi @phesse001,

Sorry for the slow response!

You are using the environment `llvm-ic-v0`, which has no observation space set, so reset() returns nothing.

This is equivalent to:
```py
>>> env = compiler_gym.make("llvm-v0", observation_space=None, reward_space="IrInstructionCount")
>>> env.reset()
None
```

Instead, you want something like:

```py
>>> env = compiler_gym.make("llvm-v0", observation_space="Autophase", reward_space="IrInstructionCount")
>>> env.reset()
array([  0,   4,  54,  39,  12,  46,  23,   6,  12,  31,   2,   4,   0,
        81,   4,  77,  13,  15, 108, 106,  75,  51,  71,  46,  15,   0,
         9,  46,   0,  13,  72,  51,  77,  81,  39,  31,   0, 163,   2,
         0,   4,   6,  13,   1,   0,  73,   8,   1,   0,  15,  85, 638,
       402,  16,  10, 298])
```

Cheers,
Chris

**Comment by phesse001** [comment]
Sorry I left out some details, I have a train function which takes in the environment as a parameter and then I call ```env.observation_space = "InstCountNorm" ```. I then call ``` test_benchmarks = env.datasets["benchmark://cbench-v1"] ``` and then try to pull a random benchmark from my dataset using ``` benchmark  = test_benchmarks.random_benchmark()``` and call ``` observation = env.reset(benchmark=benchmark) ```. Sorry for the shell example, that was me just trying to debug/simplify the problem but of course that would return None. Any idea as to why it is still returning ```None``` when I specify the observation_space like this? I can provide more code if that helps

Thanks,
Patrick

**Comment by ChrisCummins** [comment]
Thanks for the further details. Could you please paste a minimal working script to reproduce the problem?

Cheers,
Chris

**Comment by phesse001** [comment]
I figured out the issue - I was using a custom wrapper to implement 'patience' logic, but I was inheriting from gym.wrappers rather than compiler_gym.wrappers.CompilerEnvWrapper. After simply changing that inheritence my environment no longer returns None for the observation. Sorry about that - closing the issue!

**Comment by ChrisCummins** [comment]
Ah cool, glad to hear you figured it out! Having to inherit from CompilerEnvWrapper rather than the builtin wrapper base is a bit of a pain but unfortunately it's required for our API extensions.

Cheers,
Chris
