### ISSUE TITLE
Error Initializing the environment

### ISSUE THREAD

**Issue by harshraj22** [facebookresearch/CompilerGym#564]
## 🐛 Bug

```python
import gym
import compiler_gym

print(compiler_gym.COMPILER_GYM_ENVS)

# env = gym.make('llvm-codesize-v0')
env = compiler_gym.make(                 # creates a new environment (same as gym.make)
    "llvm-v0",                           # selects the compiler to use
    benchmark="cbench-v1/qsort",         # selects the program to compile
    observation_space="Autophase",       # selects the observation space
    reward_space="IrInstructionCountOz", # selects the optimization target
)
print(f'Action space: {env.action_space.shape}')
print(f'Observation space: {env.observation_space.shape}')

```

## To Reproduce

Run the above code

## Environment
![image](https://user-images.githubusercontent.com/46635452/152683494-f5635752-05be-4285-a7e0-2e2bd25476bb.png)

Please fill in this checklist:

- CompilerGym: 0.1.10
- How you installed CompilerGym (conda, pip, source): pip
- OS: Ubuntu
- Python version: 3.9.7
- Build command you used (if compiling from source):
- GCC/clang version (if compiling from source):
- Bazel version (if compiling from source):
- Versions of any other relevant libraries:

You may use the PyTorch
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
to generate most of this information. You can get the script and run it with:

```sh
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

![image](https://user-images.githubusercontent.com/46635452/152683575-7fad0c41-93cb-4b97-ac42-e2a083a6cdc8.png)

**Comment by ChrisCummins** [comment]
Hi @harshraj22, you are using Ubuntu 16.04, and unfortunately the CompilerGym pip wheel does not support any version before 18.04. You could try [building from source](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#linux), but I cannot guarantee that it would work.

Personally, I would recommend using docker to get an Ubuntu 18.04 environment, if upgrading is not viable.

Cheers,
Chris
