### ISSUE TITLE
Branch for MLIR environment

### ISSUE THREAD

**Issue by sogartar** [facebookresearch/CompilerGym#613]
@ChrisCummins, is it possible to have a branch for the MLIR env? It looks like that its merging will take a while due to its size and the `step(...)` breaking changes. We want to collaborate on it with other developers.
The branch can be called `mlir`. For the time being I would like for me and @KyleHerndon to have push access to it. Later others will join.

**Comment by ChrisCummins** [comment]
In general I try not to have long-running staging branches but I think in this case it makes total sense.

Feel free to work on `mlir` however you want and just add me to PRs when you have things you want to merge into `development`. It would be worth periodically syncing with the `development` branch as there will be the occasional breaking change that you might find useful (e.g. #591).

I've given you and Kyle push permission on this repo, let me know if there are any problems.

Cheers,
Chris
