### ISSUE TITLE
Is it possible for a baseline policy to yield a non-positive reward?

### ISSUE THREAD

**Issue by uduse** [facebookresearch/CompilerGym#614]
## ❓ Questions and Help

The [reward design here](https://compilergym.com/llvm/index.html#reward-spaces) includes a normalization based on the result of a baseline policy. However, is it possible for a baseline policy to have no improvements at all? For example, a benchmark generator generates an IR so simple that's impossible to reduce in code size.

**Comment by ChrisCummins** [comment]
> However, is it possible for a baseline policy to have no improvements at all?

Yes. It even happens that the baseline policy makes things worse, `env.observation.IrInstructionOz() > env.observation.IrInstructionCountO0()`.

To prevent scaling by zero/negative value we clamp scaling factor to a minimum value of 1:

https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/envs/llvm/llvm_rewards.py#L113

The documentation is wrong as it doesn't reflect this. [Patches welcome](https://github.com/facebookresearch/CompilerGym/blob/development/docs/source/llvm/index.rst#reward-spaces)! 🙂 

Cheers,
Chris

**Comment by uduse** [comment]
Hi @ChrisCummins sorry I'm still not sure how this is computed.

Say we have initial state cost 100, baseline cost 50, and new state cost 20, then the improvement is (100 - 20) / (100 - 50) = 1.6, right?

What is the "scaling factor" you are talking about? Is it the denominator of the previous formula? So if the initial state cost 100, baseline cost 200, and new state cost 20, does this makes the improvement (100 - 20) / max((100 - 200), 1) = 80? This seems too high to me.

**Comment by ChrisCummins** [comment]
Yes, I believe those calculations are correct.

You could instantiate a `BaselineImprovementNormalizedReward` (you may have to mock the inputs) and call `update()` on it to verify.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Closing this as having answered the original question, but happy to continue the discussion
