### ISSUE TITLE
Inheritance of action spaces and their subsets

### ISSUE THREAD

**Issue by dejangrubisic** [facebookresearch/CompilerGym#638]
## 🚀 Feature

Is it possible to inherit LLVM action space and it's subset for a custom environment? 

## Motivation

Currently, we are doing this by copying flags from LLVM action space:

llvm_env = gym.make("llvm-v0")

    action_spaces = [
        ActionSpace(
            name="llvm-hpctoolkit",
            space=Space(
                    named_discrete=NamedDiscreteSpace(
                    name=llvm_env.action_space.flags,
                )
            )
        ),
    ]

but the problem is that the ActionSpace type is NamedDiscrete instead of Commandline and it is not possible to use ConstrainedCommandline function to get a subset of action flags. Additionally Space() doesn't have a parameter that would accept Commandline either.

## Pitch
Almost always users are going to work on a subset of available action space since LLVM's ~150 flags is too large space for exploration. On the other hand, users may want to work on different subsets on the agent side in different experiments. 

## Alternatives

Work around may be to use handle_session_parameter to rewrite self.action_spaces, but the problem there that env.action_space.sample() could return out-of-range index for new action space.

Is there any other way to do this?

Cheers!

**Comment by ChrisCummins** [comment]
Hmm, interesting suggestion, will have to look into this. Would a `ConstrainedNamedDiscrete` solve your problem?

Cheers,
Chris

**Comment by dejangrubisic** [comment]
Yes, as long as we are able to say:
**example_service.py**
```
    action_spaces = [
        ActionSpace(
            name="llvm-hpctoolkit",
            space=Space(
                named_discrete=NamedDiscreteSpace(
                    name=gym.make("llvm-v0").action_space.flags,
                )
            )
        ),
    ]
```
and to use ConstrainedCommandline to constrain it.

**training_script.py**
```
env = ConstrainedCommandline(env, flags=[
        "-break-crit-edges",
        "-early-cse-memssa",
        "-gvn-hoist",
        "-gvn",
    ])
```
Cheers,
Dejan

**Comment by ChrisCummins** [comment]
Okay, I have a busy couple of weeks ahead but will try and carve out some time to take a look at this after.

Ping me after a while if there's no update 🙂 

Cheers,
Chris

**Comment by dejangrubisic** [comment]
No problem, we come up with a workaround so it is not blocking us.

See you tomorrow :)
