### ISSUE TITLE
Cache path inconsistency in cc and python?

### ISSUE THREAD

**Issue by uduse** [facebookresearch/CompilerGym#651]
I noticed that theses two files are using different conventions for creating cache paths. The cc file says the python file should align with the cc file, but they are still different. Is this intended?

https://github.com/facebookresearch/CompilerGym/blob/61f460fadee2454ff8fca3bbd5a5d338854cc4a2/compiler_gym/util/runfiles_path.py#L101-L105

https://github.com/facebookresearch/CompilerGym/blob/1596776ad35a7aeca45ed85b2e073af824844e29/compiler_gym/util/RunfilesPath.cc#L61-L65

**Comment by ChrisCummins** [comment]
Hi @uduse, that is a bug! Please patch the .py file. They should both be `~/.local/cache/compiler_gym`.

Thanks for the report, good catch!

Cheers,
Chris
