### ISSUE TITLE
Seeking step without adding action to env.actions

### ISSUE THREAD

**Issue by dejangrubisic** [facebookresearch/CompilerGym#653]
## 🚀 Feature

Adding some flag to the step that would enable user to execute the step, without adding action to env.actions

## Motivation

This would enable users to see what would observation and reward be if the action would be applied. This is useful when the agent gets the best action from the heuristic, and applies action, but the action is ineffective. In that case, we want to remove the action from env.actions

## Workaround

This could be a workaround, but it could be better to put some flag in env.step

```
                    for i, next_action in enumerate(best_actions):
                        print(f"{i}. Action = {next_action}")
                        observation, reward, done, info = env.step(
                            action=next_action,
                            observation_spaces=["perf_tensor"],
                            reward_spaces=["perf_tensor"],
                        )
                        if info.get('action_had_no_effect'):
                            env.actions.pop()
                            continue
```

**Comment by ChrisCummins** [comment]
Hmm, I'm actually not convinced this should be part of the core API. I think `env.actions` should be oblivious to whether the actions had any effect. If you want to "forget" actions that have no effect, this can be done using a wrapper:

```py
class DontTrackActionsWithNoEffect(CompilerEnvWrapper):
    """Only add action to `env.actions` if not `info['action_had_no_effect']`."""

    def step(self, action, **kwargs):
        obs, reward, info, done = self.env.step(action, **kwargs)
        if info.get('action_had_no_effect'):
            self.env.actions.pop()
        return obs, reward, info, done
```

(disclaimer: untested code). Usage:

```py
env = compiler_gym.make(...)
env = DontTrackActionWithNoEffect(env)
```

Would this do what you want?

Cheers,
Chris

**Comment by dejangrubisic** [comment]
You are the boss, you decide. 

One use-case that DontTrackActionsWithNoEffect wouldn't cover is if you have a greedy search and you want to try say 10 actions before you take 1. Some of them will actually have an effect and you would append it to the env.actions even though this is not the one you decided to take.

I know this could probably do such a thing with a fork, but I haven't tried that yet. Anyway, this may not be worth the benefit of adding complexity.

Thanks for writing wrapper classes though, I was able to integrate the 'seek' flag into my code.

Cheers,
Dejan

**Comment by ChrisCummins** [comment]
> One use-case that DontTrackActionsWithNoEffect wouldn't cover is if you have a greedy search and you want to try say 10 actions before you take 1. Some of them will actually have an effect and you would append it to the env.actions even though this is not the one you decided to take.

Not sure I follow, could you post a code snippet?

> I know this could probably do such a thing with a fork, but I haven't tried that yet. Anyway, this may not be worth the benefit of adding complexity.

Yes, if you need to "backtrack", `env.fork()` is the way to go. Something like:

```py
def pick_best_action(env, actions):
    best, a = -float("inf"), None
    for action in actions:
         with fkd as env.fork():
              _, reward, done, _ = fkd.step(action)
              if not done and reward > best:
                  best, a = reward, action
    return best
```

Cheers,
Chris

**Comment by dejangrubisic** [comment]
I see, thanks this will do it.

Cheers,
Dejan
