### ISSUE TITLE
Bug in llvm_rl benchmark when setting a max_benchmarks

### ISSUE THREAD

**Issue by qibinc** [facebookresearch/CompilerGym#654]
https://github.com/facebookresearch/CompilerGym/blob/b803856257aa663b20a26e49125d5d603f84a9b9/examples/llvm_rl/model/benchmarks.py#L96-L98

should be

`n = min(self.max_benchmarks, n)`

**Comment by ChrisCummins** [comment]
Good catch, please submit a PR!

Cheers,
Chris
