### ISSUE TITLE
Is it safe to remove everything under COMPILER_GYM_CACHE?

### ISSUE THREAD

**Issue by uduse** [facebookresearch/CompilerGym#667]
## ❓ Questions and Help

In our experiments Compiler Gym always leave "benchmark-scratch-*" directories under COMPILER_GYM_CACHE, either empty or non-empty. There could be tens of thousands of such directories and sometimes takes up TBs of diskspace.

It seems that other parts of compiler gym also uses COMPILER_GYM_CACHE for other purposes. Is it safe to remove everything under COMPILER_GYM_CACHE between runs? Currently we are removing directories with matching pattern "benchmark-scratch-*" but there are so many such directories and the removing processes takes at least tens of minutes.

**Comment by ChrisCummins** [comment]
Hi @uduse,

Yes, it is safe to delete `$COMPILER_GYM_CACHE` between runs. Aside from the `benchmark-scrtach-*` directories, the cache is used to cache downloads like dataset and runtime files. The next time you run CompilerGym those files will be re-downloaded.

Cheers,
Chris

**Comment by uduse** [comment]
Re-downloading things sounds very undesirable for me. Downloading those files could take hours (have to go through a bunch of our company's firewalls and proxies) and wouldn't that dramatically slows down the process?

**Comment by ChrisCummins** [comment]
Ah okay. If you want to see how much stuff would be re-downloaded, see `/path/to/compiler_gym/cache/downloads`.

**Comment by uduse** [comment]
What if under my cache directory there's no such `downloads` sub-directory?

**Comment by ChrisCummins** [comment]
Ah, slight correction on my previous comment. `~/.local/cache/compiler_gym/downloads` is used to cache downloaded files. In the case of the datasets, they are downloaded as tarballs and then unpacked to `~/.local/share/compiler_gym` (see [here](https://github.com/facebookresearch/CompilerGym/blob/development/compiler_gym/util/runfiles_path.py#L58)). So if you delete `~/.local/cache/compiler_gym`, it won't trigger any datasets to be re-downloaded.

Sorry for the confusion

Cheers,
Chris
