### ISSUE TITLE
Implementation of State Transition Dataset Wrapper

### ISSUE THREAD

**Issue by vladaindjic** [facebookresearch/CompilerGym#678]
## ❓ Questions and Help

Hi, @ChrisCummins , 

Sorry to interrupt. While reading [the CompilerGym paper](https://arxiv.org/pdf/2109.08267.pdf), I encountered on the State Transition Dataset Wrapper "_that asynchronously populates the Steps and Observations tables of a state transition database upon every step of an environment_." The populated dataset is then used for [offline training](https://github.com/facebookresearch/CompilerGym/blob/development/examples/gnn_cost_model/compiler_gym_dataset.py). Unfortunately, I could not find the implementation of the wrapper inside this repository. Could you please guide me to the place where I could find the implementation of this wrapper?

Thanks in advance.

Kind regards,
Vladimir

**Comment by ChrisCummins** [comment]
Hey @vladaindjic, good question. I haven't get got around to open sourcing it. Let me copy over the version from my internal repo now

**Comment by ChrisCummins** [comment]
Okay, I filed #679. It's the wrapper I used to generate the dataset we released, and isn't super extensible. If you want to change what is recorded, you would need to hack on the source. One caveat - this is a *synchronous* implementation - so the overhead of storing entries is added to compiler interactions. The async implementation still needs more work and tweaking.

Cheers,
Chris

**Comment by vladaindjic** [comment]
Hi, @ChrisCummins ,

Thanks a lot for your prompt response. :) No problem if some hack needs to be applied in order to adapt the wrapper.

Cheers,
Vladimir
