### ISSUE TITLE
[MLArchSys2022] Error "MachO doesn't support COMDATs" for mlarchsys2022.py 

### ISSUE THREAD

**Issue by biandangan** [facebookresearch/CompilerGym#685]
HI,
I downloaded the script and run it with "python mlarchsys2022.py".
% python mlarchsys2022.py
This script version: 0.0.1
Logging results to: /Users/xxx/logs/compiler_gym/mlarchsys-competition-2022/2022-05-19/21-01-07/results.csv
Using agent budget: short
Agent is deterministic? False
Number of bitcodes to optimize: 1

Evaluating benchmark 1 of 1 ...
Traceback (most recent call last):
  File "/python3.9/site-packages/compiler_gym/envs/llvm/llvm_env.py", line 321, in reset
    observation = super().reset(*args, **kwargs)
  File "/python3.9/site-packages/compiler_gym/envs/compiler_env.py", line 857, in reset
    error, reply = _call_with_error(
  File "/python3.9/site-packages/compiler_gym/envs/compiler_env.py", line 778, in _call_with_error
    return None, self.service(stub_method, *args, **kwargs)
  File "/python3.9/site-packages/compiler_gym/service/connection.py", line 821, in __call__
    return self.connection(
  File "/python3.9/site-packages/compiler_gym/service/connection.py", line 215, in __call__
    raise ValueError(e.details()) from None
ValueError: Failed to compute .text size cost. Command returned exit code 70: /Users/xxx/.local/share/compiler_gym/llvm-v0/bin/clang -w -xir - -o /Users/xxx/.cache/compiler_gym/s/0519T210107-079325-7fca/obj-4382.o -c. Error: fatal error: error in backend: MachO doesn't support COMDATs, '_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEOS8_RKS8_' cannot be lowered.
Stack dump:
0.	Program arguments: /Users/xxx/.local/share/compiler_gym/llvm-v0/bin/clang -w -xir - -o /Users/xxx/.cache/compiler_gym/s/0519T210107-079325-7fca/obj-4382.o -c 
...
clang version 10.0.0 
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Users/xxx/.local/share/compiler_gym/llvm-v0/bin

## Environment
- CompilerGym: 0.23
- How you installed CompilerGym (pip, source): pip
- OS:   macOS Big Sur 11.3 @Intel Core i7
- Python version: 3.9.1
- 

I guess the unseen program bc has COMDATs section inside.

**Comment by ChrisCummins** [comment]
Hi @valuenumbering, unfortunately our test set only supports Linux. Do you have access to a Linux environment? If not, there is a docker container for CompilerGym, though I haven't updated it to v0.2.3. Let me know if you would like this.

Apologies for omitting this constraint from the instructions, I'll update the site.

Cheers,
Chris
