### ISSUE TITLE
Adding parametric actions

### ISSUE THREAD

**Issue by dejangrubisic** [facebookresearch/CompilerGym#694]
## 🚀 Feature

Is it possible to add parametric actions to the user-defined action space? This would enable the user to specify say actions like loop unroll X, copy input X, and many more.

## Motivation

This feature is necessary for 2 kinds of actions I want to implement for LoopTool. One is split loop by X and another is copy input X (X here is the id of variable we want to copy). For split action, I currently discretize the space, but for copy input, it won't really work because that depends on the number of variables in the program.

## Pitch

To mitigate this, one potential solution that comes to mind could be to extend NamedDiscreteSpace with a special suffix that says that the action contains the parameter like "**split_X**", and then the user can say:

`env.step(... action_spaces=["split_16"])`

Another solution may be adding NamedParametrizedSpace having pair<str, int> as a type for action, although this may not be as flexible.

I guess there could be also more elegant solutions that you can find as well.

## Alternatives

I guess a workaround for everything could be using env.send_param with actions every time before env.step and just ignoring actions from there but it kinda kill the purpose of having actions in env.step.

```
env.send_param("actions", "["split_16", "up", ...]")
env.step(...action_spaces=["dummy"])
```

**Comment by ChrisCummins** [comment]
> Is it possible to add parametric actions to the user-defined action space?

I believe so, thanks to some recent improvements by @sogartar. An action space contains a `Space`:

https://github.com/facebookresearch/CompilerGym/blob/d5e1dc11b036ecc48c0ae85e90fc52fd5d10a5a4/compiler_gym/service/proto/compiler_gym_service.proto#L360-L363

And a `Space` can be an arbitrarily nested set of dicts/lists/floats/categoricals etc:

https://github.com/facebookresearch/CompilerGym/blob/d5e1dc11b036ecc48c0ae85e90fc52fd5d10a5a4/compiler_gym/service/proto/compiler_gym_service.proto#L315-L345

So you could define a tuple space where the first element is the discrete choice (split/copy) and the second element is a dictionary of params, like:

```py
env.step((action_enum.SPLIT, {"target": 16})
```

This is maybe a bit hacky, and, more importantly, some thought needs to go into how your RL agent will model the actions. I'd recommend having a think about that, as once you know how your learning agent will produce predictions, it might make it easier to see how you should expose that through an action space.

Cheers,
Chris

**Comment by dejangrubisic** [comment]
Thanks, Chris, I will take a look and come back to you if I have a question.

Cheers,
Dejan
