### ISSUE TITLE
Failed installing the required toolchain on Ubuntu 20.04

### ISSUE THREAD

**Issue by nluu175** [facebookresearch/CompilerGym#714]
## To Reproduce

1. Building the project from source following the guide at https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md 
2. Got the error when trying to install the required toolchain.

## Expected behavior

I got the error `E: Package 'clang-9' has no installation candidate` when installing the toolchain using the provided command.

## Environment

Please fill in this checklist:

- CompilerGym: n/a
- How you installed CompilerGym (pip, source): source
- OS: Ubuntu 22.04 LTS (x86_64)
- Python version: 3.8.13
- Build command you used (if compiling from source): make install
- GCC/clang version (if compiling from source): n/a (cannot install due to `E: Package 'clang-9' has no installation candidate`)
- Versions of any other relevant libraries: n/a

You may use the
[environment collection script](https://raw.githubusercontent.com/facebookresearch/CompilerGym/stable/build_tools/collect_env.py)
to generate most of this information. You can get the script and run it with:

```sh
wget https://raw.githubusercontent.com/facebookresearch/CompilerGym/stable/build_tools/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by ChrisCummins** [comment]
Hi @nluu175, if you remove the version suffix from `clang-9` to instead install `clang`, does that work? That would make the command from the INSTALL instructions:

```
sudo apt install -y clang clang-format golang libjpeg-dev \
  libtinfo5 m4 make patch zlib1g-dev tar bzip2 wget
```

**Comment by nluu175** [comment]
Hi Chris! After removing the version from clang, it worked for me. However, `make install`, after running for awhile, stills said that the `Build did Not complete succesfully`.

**Comment by ChrisCummins** [comment]
Can you provide the full output?

**Comment by nluu175** [comment]
Hi Chris! This is the output I got from running `make test` https://pastebin.com/sQGxWZvk.

**Comment by ChrisCummins** [comment]
Hi @nluu175, hmm, that's an interesting one! I haven't seen that error before.

Could you try making sure that the standard library is installed?

```
sudo apt-get install libstdc++6
```

Try that, and then run `make distclean` followed by `make test`. If it fails again, please attach the full output again.

Cheers,
Chris

**Comment by nluu175** [comment]
Hi @ChrisCummins . Thank you for your response. I tried the command you suggested but still got the errors for `make test`. Here is the output I got https://pastebin.com/iRJHtVbE

Update: I got some helps from a friend and my `make test` seems to work now. It was a problem with conda missing `ibstdc++.so.6`. Thank you so much for your help!

**Comment by ChrisCummins** [comment]
Hmm, I've not seen this error before, so I'm not sure what to suggest. The problem is caused by the underlying grpc dependency. A quick google unearthed a similar problem reported not too long ago, you could try the proposed solution: https://github.com/BVLC/caffe/issues/4953#issuecomment-258749007

Cheers,
Chris
