### ISSUE TITLE
Characterization of benchmarks for the LLVM enviroment

### ISSUE THREAD

**Issue by jaopaulolc** [facebookresearch/CompilerGym#737]
## 📚 Documentation

At this [link](https://compilergym.com/llvm/index.html#datasets), the documentation mentions that the radial plots show (in clockwise order starting from the top): 

- Average number of instructions (top);
- Density of branches (right);
- Density of **arithmetic instructions** (bottom);
- and Density of **memory operations** (left). 

However, the correct order seems to be:

- Average number of instructions (top);
- Density of branches (right);
- Density of **memory operations** (bottom);
- and Density of **arithmetic operations** (left). 

At least that is what the discussion says when contrasting `blas-v0` and `cbench-v1`, where it is said that `blas-v0` has high number of arithmetic operations and low number of memory operations.

**Comment by ChrisCummins** [comment]
Hi @jaopaulolc, you're correct, the documentation is wrong! Good catch. Please submit a patch 🙂 

Cheers,
Chris
