### ISSUE TITLE
__version__ is missing when importing gym 

### ISSUE THREAD

**Issue by JD-ETH** [facebookresearch/CompilerGym#76]
## 🐛 Bug

When trying to run some scripts in `compiler_gym/bin`, for example random_search.py
```
Traceback (most recent call last):
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/jdguo/.conda/envs/CompilerGym/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/jdguo/CompilerGym/compiler_gym/__init__.py", line 21, in <module>
    from compiler_gym.util.version import __version__  # isort:skip
ModuleNotFoundError: No module named 'compiler_gym.util.version'
```## To Reproduce

Steps to reproduce the behavior:

1. In a new environment, pip install compilerGym
2. `python -m compiler_gym.bin.random_search`

## Expected behavior

example should run. 

## Environment

Please fill in this checklist:

- CompilerGym: recent development branch
- How you installed CompilerGym (conda, pip, source): pip install in conda env
- OS: Mac 
- Python version: 3.8
- Build command you used (if compiling from source):
- GCC/clang version (if compiling from source):
- Bazel version (if compiling from source):
- Versions of any other relevant libraries:

You may use the PyTorch
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
to generate most of this information. You can get the script and run it with:

```sh
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by hughleat** [comment]
Ooh, did you do this from inside the git repo? I get this if I call `python -m compiler_gym.bin....` from inside CompilerGym/.
If I move out to some other directory it works.
Can you check if that fixes it for you?

Then, I think you may also need to download a dataset first: python -m compiler_gym.bin.datasets ... or my new favourite python -m compiler_gym.bin.manual_env -env=llvm-v0

Plus, you may need `-env=llvm-v0 -reward=IrInstructionCount -benchmark=cBench-v0/adpcm'. or similar.

(BTW, if you could try the shell with `python -m compiler_gym.bin.manual_env -env=llvm-v0`, I would be delighted to get your feedback as I've only just finished it.)

**Comment by hughleat** [comment]
Then, I think you may also need to download a dataset first: `python -m compiler_gym.bin.datasets ...` or my new favourite `python -m compiler_gym.bin.manual_env -env=llvm-v0`

Plus, you may need `-env=llvm-v0 -reward=IrInstructionCount -benchmark=cBench-v0/adpcm'. or similar.

**Comment by JD-ETH** [comment]
Yeah it works when I'm outside of the folder, thanks. 

the command line interface is pretty cool! 138 actions are scary for a compiler-outsider like me though :D What does the `commandline` option do? Command for executing all steps so far? @hughleat

**Comment by hughleat** [comment]
:) thanks!

Command line gives approximately what you would ask LLVM to do outside the
gym to Schreiber the same effect.

The action space will get massive some day :)

**Comment by ChrisCummins** [comment]
Yes sorry about this. The error message is really unclear. Filing #78, lemme know if that helps clarify.

New error message:

```
$ python -c 'import compiler_gym'
...
ModuleNotFoundError: No module named 'compiler_gym.util.version'.
Are you running in the root of the CompilerGym repository?
If so, please change to a different directory so that `import compiler_gym` will work.
```
