### ISSUE TITLE
Call env.require_dataset() when required

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#79]
## 🚀 Feature

If a benchmark is requested that is not installed but belongs to an available dataset, we could just implicitly call `env.require_dataset()` rather than throwing an error.

**Comment by hughleat** [comment]
I like it. 
Are any of the datasets big though? Possibly would be better if the dataset was more fine grained.

**Comment by ChrisCummins** [comment]
`env.require_dataset("github-v0")` will trigger a 300+mb download. Maybe we don't want to hide that from the user. Definitely seems worth waiting until #45 is merged as that may change this

**Comment by hughleat** [comment]
Just a small thought... What about shipping cBench by default? That way everyone gets something to start with and there's none of this - "D'oh, another step you're making me take just to play with this thing?"

**Comment by ChrisCummins** [comment]
Good idea. Please file an issue! :)

**Comment by ChrisCummins** [comment]
Done.
