### ISSUE TITLE
GLIBC version not found (required by ./compiler_gym-llvm-service)

### ISSUE THREAD

**Issue by dejangrubisic** [facebookresearch/CompilerGym#791]
## ❓ Questions and Help

I am trying to install CompilerGym on the school cluster with GLIBC_2.17. I am able to pip install CompilerGym, but when I run:

 `compiler_gym.make("llvm-v0") # or gym.make("llvm-v0")`

 I am getting the error:

```
 ./compiler_gym-llvm-service: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./compiler_gym-llvm-service)
./compiler_gym-llvm-service: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./compiler_gym-llvm-service)
```
Since GLIBC is the core library of OS, it is hard to install it without sudo rights. Do you know the way this problem could be bypassed?

**Comment by ChrisCummins** [comment]
It sounds like your school's cluster is running an older OS. Currently we only support fairly [recent distros](https://github.com/facebookresearch/CompilerGym/blob/development/INSTALL.md#installation). Your two options are:

1. Build from source on the school OS.
2. Run inside a container like docker.

The second option may be easier.

Cheers,
Chris

**Comment by dejangrubisic** [comment]
Thank you, Chris, this makes sense. I ended up creating a container that works as expected :)

**Comment by ChrisCummins** [comment]
Glad to hear!
