### ISSUE TITLE
I build compiler_gym from source with Bazel . After "make install", I meet the problem below. How can I solve it?

### ISSUE THREAD

**Issue by sunpeng2020** [facebookresearch/CompilerGym#800]
## ❓ Questions and Help

I build compiler_gym from source with Bazel . After "make install", I meet the problem below. How can I solve it?
## Additional Context
FAILED: Build did NOT complete successfully (36 packages loaded, 12467 targets configured)
    currently loading: @com_github_grpc_grpc//src/compiler
make: *** [Makefile:181: bazel-build] Error 1

**Comment by ChrisCummins** [comment]
Hi @sunpeng2020, I'll need more context. Can you refile this as a bug using [the template](https://github.com/facebookresearch/CompilerGym/issues/new?assignees=&labels=Bug&projects=&template=--bug-report.md&title=) to provide the needed info? Thanks.

Chris
