### ISSUE TITLE
Do CompilerGym have LLVM Flag Tuning?

### ISSUE THREAD

**Issue by libin049** [facebookresearch/CompilerGym#801]
## ❓ Questions and Help

 CompilerGym has LLVM phase ordering and GCC flag tuning. Do CompilerGym have LLVM flag tuning like GCC flag tuning? LLVM also has parameterized command line flags such as -inline-threshold=number. It seems that LLVM phase ordering cannot process command line flags like -inline-threshold=number.

**Comment by libin049** [comment]
@ChrisCummins Could you answer above question?

**Comment by ChrisCummins** [comment]
Sorry for delay! No, the LLVM environment does not support flag tuning. It's on [our roadmap](https://compilergym.com/about.html#enabling-increasingly-granular-control-over-optimization-decisions) but no timeline yet.

Your have two options:

1. Add new actions to the LLVM environment which set the options exposed as command line flags, such as [inline threshold](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/InlineCost.cpp#L74-L76) you gave as an example.
2. Create a new environment which wraps opt/clang and runs these actions from the command line. You could start with the GCC environment as a base, and use the LLVM datasets to get you started.

Cheers,
Chris
