### ISSUE TITLE
I use cmake to build from source, but I met the problem below. How can I solve it ?

### ISSUE THREAD

**Issue by sunpeng2020** [facebookresearch/CompilerGym#802]
## 🐛 Bug

I used cmake to build from source, but I met the problem below. How can I solve it ?

## To Reproduce

1.cd CompilerGym/build
2.cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S ../ -B ./

error messages:
'/home/data2/sp/.local/bin/cmake' '-G' 'Ninja' '-C' '/home/data2/sp/CompilerGym/build/external/boost/boost_initial_cache.cmake' '-S' '/home/data2/sp/CompilerGym/external/boost' '-B' '/home/data2/sp/CompilerGym/build/external/boost' '-D' 'CMAKE_INSTALL_PREFIX=/home/data2/sp/CompilerGym/build/external/boost/install'
loading initial cache file /home/data2/sp/CompilerGym/build/external/boost/boost_initial_cache.cmake
'/usr/bin/git' '--version'
'/usr/sbin/sysctl' '-n' 'hw.ncpu'
'/usr/bin/nproc'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/data2/sp/CompilerGym/build/external/boost
'/home/data2/sp/.local/bin/cmake' '--build' '/home/data2/sp/CompilerGym/build/external/boost'
[1/7] Performing download step (git clone) for 'boost'
FAILED: boost/src/boost-stamp/boost-download 
cd /home/data2/sp/CompilerGym/build/external/boost/boost/src && /home/data2/sp/.local/bin/cmake -P /home/data2/sp/CompilerGym/build/external/boost/boost/tmp/boost-gitclone.cmake && /home/data2/sp/.local/bin/cmake -E touch /home/data2/sp/CompilerGym/build/external/boost/boost/src/boost-stamp/boost-download
Cloning into 'boost'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'boost'...
fatal: unable to access 'https://github.com/boostorg/boost.git/': GnuTLS recv error (-54): Error in the pull function.
Cloning into 'boost'...
fatal: unable to access 'https://github.com/boostorg/boost.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
-- Had to git clone more than once:
          3 times.
CMake Error at /home/data2/sp/CompilerGym/build/external/boost/boost/tmp/boost-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/boostorg/boost.git'

ninja: build stopped: subcommand failed.
CMake Error at build_tools/cmake/build_external_cmake_project.cmake:37 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"

Call Stack (most recent call first):
  external/external.cmake:386 (build_external_cmake_project)
  CMakeLists.txt:86 (include)

-- Configuring incomplete, errors occurred!
See also "/home/data2/sp/CompilerGym/build/CMakeFiles/CMakeOutput.log".
See also "/home/data2/sp/CompilerGym/build/CMakeFiles/CMakeError.log".

## Environment

Please fill in this checklist:

- CompilerGym: 0.2.5
- How you installed CompilerGym (pip, source):use cmake from source
- OS:Ubuntu 20.04.6 LTS (x86_64)
- Python version:3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
- Build command you used (if compiling from source):cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S ../ -B ./ 
- GCC/clang version (if compiling from source):Clang version: 8.0.1 (tags/RELEASE_801/final)
- Versions of any other relevant libraries:
CMake version: version 3.20.5
Libc version: glibc-2.31
You may use the
[environment collection script](https://raw.githubusercontent.com/facebookresearch/CompilerGym/stable/build_tools/collect_env.py)
to generate most of this information. You can get the script and run it with:

```sh
wget https://raw.githubusercontent.com/facebookresearch/CompilerGym/stable/build_tools/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by ChrisCummins** [comment]
Were you able to fix this issue?

**Comment by sunpeng2020** [comment]
yes. I have solved it.  I download the boost source code and put it into the project.
