### ISSUE TITLE
I want to use runtime as reward. so I need a runnable benchmark. How can I know which benchmark is runnable?

### ISSUE THREAD

**Issue by sunpeng2020** [facebookresearch/CompilerGym#806]
## ❓ Questions and Help

I want to use runtime as reward. so I need a runnable benchmark. How can I know which benchmark is runnable? 
If I want to use my own source files to make a runnable benchmark to test it in compilergym , What shoud I do?

**Comment by sunpeng2020** [comment]
I have solved it .

**Comment by alexeybelkov** [comment]
@sunpeng2020 Hey! I also want to create my own runnable benchmark. Can you please share how did y solve this?
