### ISSUE TITLE
After I change llvm version in CompilerGym, I find many datasets do work. How to solve the problem?

### ISSUE THREAD

**Issue by sunpeng2020** [facebookresearch/CompilerGym#808]
## ❓ Questions and Help

I change the llvm version from 10.0.0 to 8.0.1 in CompilerGym. But I find many datasets and benchmarks do work. I think it's because the  .bc files in the benchmarks  are compiled by llvm 10.0.0, but now the llvm version is 8.0.1, so there is a version collision. The llvm 8.0.1 can deal with the compiled .bc files of the benchmarks of CompilerGym. If I want to use the datasets and benchmarks provided by CompilerGym, how can I sovle the problem?

**Comment by ChrisCummins** [comment]
Hi @sunpeng2020, we made the decision when first building CompilerGym to prefer shipping benchmarks as LLVM bitcodes, which unfortunately means that changing LLVM versions will likely break things, as you have noticed.

Note some benchmarks are compiled from C/C++ source and so will work fine with LLVM-8:
- benchmark://anghabench-v1
- benchmark://jotaibench-v0
- generator://csmith-v0

Also generator://llvm-stress-v0 should be easy to port to LLVM-8 by just swapping the `llvm-stess` binary for the correct version.

For all other datasets the only option would be to build equivalent new ones from source. 

Cheers,
Chris
