### ISSUE TITLE
Why the ActionSpace in llvm do not contain analysis passes?

### ISSUE THREAD

**Issue by sunpeng2020** [facebookresearch/CompilerGym#819]
## ❓ Questions and Help

I want to know why the ActionSpace in llvm do not contain analysis passes? Should not we consider both anaylsis pass and transform pass when we are searching the best pass sequence?

**Comment by yingluosanqian** [comment]
I think the 'pass manager' in llvm would automatically call the analysis pass when a transform pass being executed.

**Comment by ChrisCummins** [comment]
Yep @yingluosanqian is right. We expose the *transform* passes and let the pass manager handle the rest, same as using `opt` from the command line.

Cheers,
Chris
