### ISSUE TITLE
commit

### ISSUE THREAD

**Issue by booski360** [facebookresearch/CompilerGym#90]
## 📚 Documentation

request approved

**Comment by ChrisCummins** [comment]
Hi there, not sure that I understand :) Is there a particular issue?

Cheers,
Chris

**Comment by booski360** [comment]
Sorry I got like 10 million things going on my desktop I'll correct it

**Comment by ChrisCummins** [comment]
Hehe, not to worry. Please file a new issue when ready.

Cheers,
Chris
